CREATE DATABASE IF NOT EXISTS  seacatcode_mini_analytics;
USE seacatcode_mini_analytics;

CREATE TABLE IF NOT EXISTS UK_LIST (
	CODE VARCHAR(30) NOT NULL PRIMARY KEY
)

CREATE TABLE IF NOT EXISTS PING_LIST (
	T BIGINT UNSIGNED NOT NULL,
	CODE VARCHAR(30) NOT NULL,
	INDEX PING_IDX (T,CODE)
)

## INSERT UK_LIST (CODE) VALUES('VALUE1');